sadmin.framework:CreateRank("root", 100,{
    ban = true,
    unarrest = true,
    goto = true,
    bring = true,
    addmoney = true,
    sethunger = true,
    arrest = true,
    setmoney = true,
    setgroup = true,
    wanted = true,
    kill = true,
    spawn = true,
    freeze = true,
    setjob = true,
}, Material("icon16/tux.png"))